import Link from "next/link";
import { User } from "lucide-react";

const DolphinLogo = ({ className = "text-2xl" }: { className?: string }) => (
  <span className={`inline-block grayscale opacity-80 select-none ${className}`} style={{ lineHeight: 1 }}>🐋</span>
);

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900 font-sans flex flex-col selection:bg-pink-100">
      <nav className="sticky top-0 z-50 w-full border-b border-slate-200 bg-white/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-8">
            <Link href="/" className="font-bold tracking-tight text-slate-900 text-lg flex items-center gap-2 hover:opacity-80 transition-opacity">
              <DolphinLogo /> Tonina.me
            </Link>
            <div className="hidden md:flex items-center gap-6 text-sm font-medium text-slate-600">
              <Link href="/concept-explorer" className="hover:text-slate-900 transition-colors">Concept Explorer</Link>
              <Link href="/wealth" className="hover:text-slate-900 transition-colors">Tonina Wealth</Link>
              <Link href="/lab" className="hover:text-slate-900 transition-colors">The Lab</Link>
              <Link href="/blog" className="hover:text-slate-900 transition-colors">Tonina Blog</Link>
            </div>
          </div>
        </div>
      </nav>

      <div className="flex-1 max-w-3xl mx-auto px-6 py-16 w-full">
        <h1 className="text-4xl font-bold tracking-tight text-slate-900 mb-8">Terms of Service & Disclaimer</h1>
        
        <div className="prose prose-slate max-w-none prose-h2:text-xl prose-h2:font-bold prose-h2:mt-8 prose-h2:mb-4 prose-p:text-sm prose-p:leading-relaxed prose-p:text-slate-600">
          <div className="bg-rose-50 border border-rose-200 p-6 rounded-xl mb-8">
            <h2 className="text-rose-800 !mt-0 !mb-2 uppercase tracking-widest text-xs">Not Financial Advice</h2>
            <p className="text-rose-700 !mt-0 font-medium">
              The content, calculators, tools, and simulations provided on Tonina.me are strictly for educational and informational purposes only. I am not a certified financial planner, registered investment advisor, or broker-dealer. Nothing on this website constitutes professional financial, legal, or tax advice. You are solely responsible for your own financial decisions.
            </p>
          </div>

          <h2>1. Educational Purpose & Information Accuracy</h2>
          <p>
            Tonina.me is a personal portfolio and educational platform. While the financial data and corporate case studies (e.g., 10-K teardowns) are gathered from public filings and sources believed to be reliable, I make no guarantees regarding their absolute accuracy, completeness, or timeliness. Models and projections generated by tools like "The Scenario Planner" are hypothetical simplifications and do not reflect guaranteed future outcomes.
          </p>

          <h2>2. Use of Tools and Platforms</h2>
          <p>
            The interactive tools and spreadsheets provided on this site are provided "as is" and "as available," without any warranties, express or implied. Tonina.me and its creator assume no liability for any software bugs, data losses, or financial miscalculations resulting from the use of these tools.
          </p>

          <h2>3. Monetization and Advisory Offerings</h2>
          <p>
            Unless explicitly stated otherwise, the content on this site is free and educational. However, I reserve the right to offer paid 1:1 advisory sessions, premium templates, or sponsored content in the future. Any paid advisory sessions are for strategic consulting and generalized planning, not formal fiduciary wealth management.
          </p>

          <h2>4. Intellectual Property</h2>
          <p>
            The original code, writing, and design elements of Tonina.me are my intellectual property. You may not scrape, clone, or commercially repackage the tools and essays found here without explicit written permission.
          </p>

          <h2>5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Tonina.me and its creator shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including any loss of profits or revenues, incurred from your use of the website or its tools.
          </p>
          
          <p className="text-xs text-slate-400 mt-12 italic">Last Updated: March 2026</p>
        </div>
      </div>
    </main>
  );
}